blueprint: 0
name: service-java
title: Specgen Java Service
roots: [common, build, src]
args:
  project_name:
    type: string
    description: project name
    default: the-service
  build:
    type: string
    description: build system
    values: [maven, gradle]
    default: maven
  group_id:
    type: string
    description: project group id
    default: com.company
  server:
    type: string
    description: server framework
    values: [spring, micronaut]
    default: spring
  jsonlib:
    type: string
    description: JSON library
    values: [jackson, moshi]
    default: jackson
  package_name:
    type: string
    description: java package name
    default: theservice
  main_class:
    type: string
    description: java main class
    default: MyApplication
  swagger:
    type: boolean
    description: do you want to enable swagger generation and hosting
    default: yes
  versions:
    type: map
    description: libraries versions
    keys:
      specgen:
        type: string
        description: specgen version
        noinput: true
        default: 2.1.1591
      springfox:
        type: string
        description: springfox version
        noinput: true
        default: 3.0.0
      spring_boot:
        type: string
        description: spring boot version
        noinput: true
        default: 2.5.5