blueprint: 0
name: service-java
title: Specgen Java Service
roots: [maven, code]
ignore: []
args:
  project_name:
    type: string
    description: project name
    default: the-service
  build_system:
    type: string
    description: build system
    values: [maven, gradle]
    default: maven
  group_id:
    type: string
    description: project group id
    default: com.company
  server:
    type: string
    description: server framework
    values: [spring, micronaut]
    default: spring
  jsonlib:
    type: string
    description: JSON library
    values: [jackson, moshi]
    default: jackson
  package_name:
    type: string
    description: java package name
    default: theservice
  versions:
    type: map
    description: libraries versions
    keys:
      specgen:
        type: string
        description: specgen version
        default: 2.1.1591