blueprint: 0
name: service-java
title: Specgen Java Service
rename: {"gitignore": ".gitignore"}
args:
  project_name:
    type: string
    description: project name
    default: the-service
  build:
    type: string
    description: build system
    values: [maven, gradle-kotlin, gradle-groovy]
    default: maven
  group_id:
    type: string
    description: project group id
    default: com.company
  server:
    type: string
    description: server framework
    values: [spring, micronaut]
    default: spring
  jsonlib:
    type: string
    description: JSON library
    values: [jackson, moshi]
    default: jackson
  package_name:
    type: string
    description: java package name
    default: theservice
  main_class:
    type: string
    description: java main class
    default: MyApplication
  swagger:
    type: boolean
    description: do you want to enable swagger generation and hosting
    default: yes
  versions:
    type: map
    description: libraries versions
    keys:
      specgen:
        type: string
        description: specgen version
        noinput: true
        default: 2.1.1638
      springfox:
        type: string
        description: springfox version
        noinput: true
        default: 3.0.0
      spring_boot:
        type: string
        description: spring boot version
        noinput: true
        default: 2.5.5
      spring_dependency:
        type: string
        description: spring dependency management plugin version
        noinput: true
        default: 1.0.11.RELEASE 
      micronaut:
        type: string
        description: micronaut version
        noinput: true
        default: 3.4.2
      micronaut_application:
        type: string
        description: micronaut application plugin version
        noinput: true
        default: 3.3.2  
      jsr305:
        type: string
        description: jsr305 version
        noinput: true
        default: 3.0.2
      jakarta:
        type: string
        description: jakarta annotation version
        noinput: true
        default: 2.1.0  
      moshi:
        type: string
        description: moshi version
        noinput: true
        default: 1.13.0