name: client-ts
on:
  push:
    paths:
      - .github/variables/**
      - .github/actions/**
      - .github/workflows/client-ts.yml
      - client-ts/**
  workflow_dispatch: {}
jobs:
  client-ts:
    strategy:
      matrix:
        client: [axios, browser-fetch, node-fetch]
        validation: [superstruct, iots]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setvars

      - uses: ./.github/actions/getrendr
        with:
          jfrog_pass: ${{ secrets.JFROG_PASS }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Rendr template
        run: |
          ./rendr render -set client=${{ matrix.client }} -set validation=${{ matrix.validation }} -set versions.specgen=${SPECGEN_VERSION} -noinput -out output file:///. client-ts

      - uses: ./.github/actions/runbuild
        with:
          path: output