name: client-java
on:
  workflow_dispatch: {}
  push:
    paths:
      - client-java/**
      - .github/client-java.yml
  workflow_dispatch: {}
jobs:
  client-java:
    strategy:
      matrix:
        build: [maven, gradle-kotlin, gradle-groovy]
        client: [okhttp]
        jsonlib: [jackson, moshi]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.1.0
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Get rendr
        run: |
          curl -L -H "X-JFrog-Art-Api:${{ secrets.JFROG_PASS }}" -O "https://specgen.jfrog.io/artifactory/binaries/rendr/latest/rendr_linux_amd64.zip"
          unzip -o rendr_linux_amd64.zip
          ./rendr help

      - name: Test client-java
        run: |
          ./rendr render -set build=${{ matrix.build }} -set client=${{ matrix.client }} -set jsonlib=${{ matrix.jsonlib }} -set versions.specgen=2.1.1794 -noinput -out output file:///. client-java
          cd output
          $(../rendr build .)