name: service-kotlin
on:
  push:
    paths:
      - .github/variables/**
      - .github/actions/**
      - .github/workflows/service-kotlin.yml
      - service-kotlin/**
  workflow_dispatch: {}
jobs:
  service-kotlin:
    strategy:
      matrix:
        build: [maven, gradle-groovy, gradle-kotlin]
        server: [micronaut]
        jsonlib: [jackson, moshi]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Environment Variables
        uses: ./.github/actions/setvars

      - uses: actions/setup-java@v3.1.0
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Get rendr
        run: |
          curl -L -H "X-JFrog-Art-Api:${{ secrets.JFROG_PASS }}" -O "https://specgen.jfrog.io/artifactory/binaries/rendr/latest/rendr_linux_amd64.zip"
          unzip -o rendr_linux_amd64.zip
          ./rendr help

      - name: Test service-kotlin
        run: |
          ./rendr render -set build=${{ matrix.build }} -set server=${{ matrix.server }} -set jsonlib=${{ matrix.jsonlib }} -set versions.specgen=${SPECGEN_VERSION} -noinput -out output file:///. service-kotlin
          cd output
          $(../rendr build .)