name: service-kotlin
on:
  push:
    paths:
      - .github/variables/**
      - .github/actions/**
      - .github/workflows/service-kotlin.yml
      - service-kotlin/**
  workflow_dispatch: {}
jobs:
  service-kotlin:
    strategy:
      matrix:
        build: [maven, gradle-groovy, gradle-kotlin]
        server: [micronaut]
        jsonlib: [jackson, moshi]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setvars

      - uses: ./.github/actions/getrendr
        with:
          jfrog_pass: ${{ secrets.JFROG_PASS }}

      - uses: actions/setup-java@v3.1.0
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Rendr template
        run: |
          ./rendr render -set build=${{ matrix.build }} -set server=${{ matrix.server }} -set jsonlib=${{ matrix.jsonlib }} -set versions.specgen=${SPECGEN_VERSION} -noinput -out output file:///. service-kotlin

      - uses: ./.github/actions/runbuild
        with:
          path: output