name: service-go
on:
  push:
    paths:
      - .github/variables/**
      - .github/actions/**
      - .github/workflows/service-go.yml
      - service-go/**
  workflow_dispatch: {}
jobs:
  service-go:
    strategy:
      matrix:
        server: [vestigo]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setvars

      - uses: ./.github/actions/getrendr
        secrets:
          JFROG_PASS: ${{ secrets.JFROG_PASS }}

      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.0'

      - name: Test service-go
        run: |
          ./rendr render -set server=${{ matrix.server }} -set versions.specgen=${SPECGEN_VERSION} -noinput -out output file:///. service-go
          export BUILD_COMMANDS=$(rendr build output)
          cd output
          echo "Build commands:"
          echo "$BUILD_COMMANDS"
          echo "$BUILD_COMMANDS" | while read BUILD_COMMAND ; do
            echo "Executing: $BUILD_COMMAND"
            $BUILD_COMMAND
          done