name: Test templates
on: [push, workflow_dispatch]
jobs:
  test-service-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.1.0
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'maven'

      - name: Get rendr
        run: |
          curl -L -H "X-JFrog-Art-Api:${{ secrets.JFROG_PASS }}" -O "https://specgen.jfrog.io/artifactory/binaries/rendr/latest/rendr_linux_amd64.zip"
          unzip -o rendr_linux_amd64.zip
          ./rendr -help

      - name: Test service-java
        run: |
          ./rendr -set build=maven -set server=spring -set jsonlib=jackson -set versions.specgen=2.1.1559 -noinput -out output file:///. service-java
          cd output
          chmod +x mvnw
          ./mvnw compile